### ISSUE TITLE
Could also collect editor information

### ISSUE THREAD

**Issue by dieterdreist** [joto/taginfo#173]
Would it be possible to add a count for editor (software), so that you know for every tag (from the changesets) through which editor it has been added? This could be useful to find possible distortions caused by software (e.g. from presets or autocompletion, e.g. tags that are only set by one editor might be typos or undocumented tags or for things where there are more frequently used alternatives).

**Comment by joto** [comment]
While this sounds like something that's easy to do I expect it to be not so easy. First we'd have to figure out which editor is responsible for each changeset. Because there is no real defined format for that it is a lot of guesswork. We can probably only detect the large editors reliably. Then we have to detect the specific release or version, or maybe ranges of versions etc. And then we have to to figure out which tags was added in which changeset. For this we need to the full history planet. So taginfo would have to look at the changeset dump and full history dump for this, both it doesn't currently look at. This would add a lot amount of extra work for something that's not really taginfos mission. This might be better done as a separate piece of software if somebody wants to take this on. We can always feed back the results to taginfo using the projects mechanism.
