### ISSUE TITLE
don't show wikipages marked for deletion with "✔"

### ISSUE THREAD

**Issue by RicoZ-OSM** [joto/taginfo#66]
Taginfo will show which tag/value combinations have an wikipage - for most people this is an important hint that it is a valid combination. Apparently much fewer people do follow the link.

As it happens, the wiki has a huge backlog of pages that should be deleted but aren't ( http://wiki.openstreetmap.org/wiki/Category:Labelled_for_deletion ) and taginfo readily displays  those with wiki-entry "✔"  - fooling mappers into believing that it is a legal value.

Examples:
* http://taginfo.openstreetmap.org/tags/bridge=suspension#wiki
* http://taginfo.openstreetmap.org/tags/bridge=swing#wiki
* http://taginfo.openstreetmap.org/tags/bridge=drawbridge#wiki

**Comment by brycenesbitt** [comment]
+1 on fixing this.   I'm not sure that "pages marked for deletion" need special treatment, nor proposals that are simply inactive.  But on occasion you have a tag that really should not be used any more.  A red "X" rather than a checkbox would help:

{{ValueDescription
| key           = denotation
| value         = cluster
| status        = deprecated
}}

![image](https://cloud.githubusercontent.com/assets/1294423/6766901/97027c4e-cfd6-11e4-9650-429a2cfe03a1.png)

That would be:
http://wiki.openstreetmap.org/wiki/Category:Tag_descriptions_with_status_%22deprecated%22
http://wiki.openstreetmap.org/wiki/Category:Tag_descriptions_with_status_%22abandoned%22

**Comment by joto** [comment]
There is nothing to fix here. The `status` field in key/tag description is based on some totally arbitrary decision making process, they are not a good basis for decisions what tags to use and what not. You have to actually look at the wiki page and read whats on there to fully understand the case. Taginfo can not understand the complexity behind all that, so all it does is give you a hint that there is a wiki page there and you have to look at it.
And some pages I marked for deletion were fixed the next day, so this doesn't seem to be an issue either.

**Comment by brycenesbitt** [comment]
The difference between "defacto" and "approved" is indeed arbitrary.

The wiki tags marked deleted/deprecated however do have a consistency to them: as of now all of those look legitimate.
The other potential source of deleted/deprecated information is JOSM's validator.

**Comment by joto** [comment]
@brycenesbitt please keep to the topic at hand and stop discussing closed issues. Use the mailing lists or so for discussions. Issues are for reporting and tracking specific issues with tagifo and not suitable for general discussions.
